# -*- coding: utf-8 -*-
"""Every Tuning key must be reachable from the embedded console.

A key added to `Tuning::table()` is served by `/api/tuning` the moment it
exists, so it LOOKS finished — but the console is hand-written HTML and only
grows a control if somebody remembers. A setting nobody can find is, in
practice, a setting that does not exist: it gets re-implemented, or worse,
reported as a missing feature it already has.

This compares the two lists. The console reaches a key in one of two ways:

  * a row in the declarative `TUN=[...]` table (renders a slider), or
  * a hand-written control naming it — `T('key', ...)`, an `o_key` checkbox,
    or a direct `/api/tuning?key=` URL.

Run:  python scripts/gates/check-console.py
Exits 1 on any problem, so it can gate a commit hook or CI.

WHY NOT parse the HTML: it is a C++ raw string literal holding a page whose
controls are generated by JavaScript at runtime. Matching the KEY NAME is what
the maintainer actually has to get right, and it has no false positives — a key
named in the console but wired to nothing would still be a bug this cannot see,
which is why the list of exceptions below is spelled out by hand rather than
inferred.
"""
import io
import os
import re
import sys

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

# The repo root, from `scripts/gates/` — three levels up. ASSERTED and not
# assumed: a wrong root does not crash here, it makes every path below miss and
# the run reads like a broken repository instead of a moved script.
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))))
assert os.path.isfile(os.path.join(ROOT, 'platformio.ini')), \
    'repo root not found from ' + __file__

# Keys that are deliberately NOT console controls. Each one states why, because
# an unexplained exception list is how a gate quietly stops gating.
EXEMPT = {
    # Written by POST /api/statusbar?mode=, which the console DOES drive
    # through the band-mode buttons. Exposing it a second time as a raw number
    # would give the same setting two controls that could disagree.
    'band_mode': 'driven by the band-mode buttons via /api/statusbar',
    # The schema version of config.yaml. It is machinery for the migration on
    # load, not a preference; a user turning it would silently re-default the
    # keys recalibrated since that version.
    'cfg_version': 'internal schema version, never a user setting',
}


def keys_of_tuning(src):
    body = src.split('static const Entry* table()')[1].split('return T;')[0]
    return re.findall(r'\{\s*"([a-z0-9_]+)"\s*,\s*&Tuning::', body)


def main():
    tun = io.open(os.path.join(ROOT, 'src', 'engine', 'Tuning.h'),
                  encoding='utf-8').read()
    con = io.open(os.path.join(ROOT, 'src', 'app', 'WebConsole.h'),
                  encoding='utf-8').read()

    keys = keys_of_tuning(tun)
    sliders = set(re.findall(r'\["([a-z0-9_]+)"',
                             con.split('const TUN=[')[1].split('];')[0]))

    problems = 0
    missing = []
    for k in keys:
        if k in EXEMPT or k in sliders:
            continue
        if any(re.search(p, con) for p in (r"T\(\s*['\"]%s['\"]" % k,
                                           r"o_%s\b" % k,
                                           r"tuning\?%s=" % k)):
            continue
        missing.append(k)

    for k in missing:
        print('ABSENT  %s : aucun controle dans la console' % k)
        problems += 1

    # A slider naming a key that no longer exists writes a value nothing reads.
    for k in sorted(sliders - set(keys)):
        print('ORPHELIN %s : curseur de console sans cle Tuning' % k)
        problems += 1

    # The language is not a Tuning key (it lives in config.yaml `lang:`), and
    # it is the one setting that decides whether the page can be READ at all.
    if not re.search(r"api/config\?lang=", con):
        print('ABSENT  lang : pas de bascule de langue dans la console')
        problems += 1

    print('%d cle(s) de tuning, %d exemptee(s), %d probleme(s)'
          % (len(keys), len(EXEMPT), problems))
    return 1 if problems else 0


if __name__ == '__main__':
    sys.exit(main())
