// GENERE par extract-presets.py — NE PAS EDITER A LA MAIN.
// Sources : src/engine/presets/*.h, Emotions.h, EyeRig.h
// Relancer le script apres toute modification de l'un des trois.
// Charge en <script> simple, pas un module ES : l'editeur doit
// s'ouvrir d'un double-clic, or file:// bloque les modules.
window.PRESETS = {
  "Angry": {
    "Height": 50,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 30,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 5,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.3,
    "Width": 100
  },
  "Annoyed": {
    "Height": 30,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 25,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 0,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 100
  },
  "Annoyed_Alt": {
    "Height": 12,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 9,
    "OuterIsLeft": 0,
    "Radius_Bottom": 10,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 0,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 100
  },
  "Awe": {
    "Height": 112,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 40,
    "Radius_Bottom_Outer": 48,
    "Radius_Top": 40,
    "Radius_Top_Outer": 46,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 112
  },
  "Contempt_Normal": {
    "Height": 75,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 20,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 20,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 100
  },
  "Contempt_Squint": {
    "Height": 28,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": -5,
    "OuterIsLeft": 0,
    "Radius_Bottom": 18,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 3,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.25,
    "Width": 95
  },
  "Curious_Big": {
    "Height": 104,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 30,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 30,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 105
  },
  "Curious_Normal": {
    "Height": 68,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 18,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 18,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 92
  },
  "Dead": {
    "Height": 5,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 0,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 0,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 70
  },
  "Disgust": {
    "Height": 28,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": -3,
    "OuterIsLeft": 0,
    "Radius_Bottom": 18,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 0,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 100
  },
  "Doubt": {
    "Height": 65,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 22,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 15,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.08,
    "Width": 95
  },
  "Excited": {
    "Height": 110,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 5,
    "OuterIsLeft": 0,
    "Radius_Bottom": 35,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 35,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 112
  },
  "Focused": {
    "Height": 35,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 2,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 8,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.2,
    "Width": 100
  },
  "Frozen": {
    "Height": 45,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 8,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 8,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 100
  },
  "Frustrated": {
    "Height": 30,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": -12,
    "OuterIsLeft": 0,
    "Radius_Bottom": 25,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 0,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 100
  },
  "Furious": {
    "Height": 75,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 20,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 5,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.4,
    "Width": 100
  },
  "Glee": {
    "Height": 20,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 12,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 40,
    "OuterIsLeft": 0,
    "Radius_Bottom": 0,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 20,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 100
  },
  "Happy": {
    "Height": 25,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 0,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 25,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 100
  },
  "Nervous": {
    "Height": 88,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": -8,
    "OuterIsLeft": 0,
    "Radius_Bottom": 20,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 20,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 88
  },
  "Nervous_Alt": {
    "Height": 50,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 20,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 12,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 12,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 50
  },
  "Normal": {
    "Height": 100,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 20,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 20,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 100
  },
  "Normal_Alt": {
    "Height": 92,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 20,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 20,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 100
  },
  "Questioning_Big": {
    "Height": 104,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": -8,
    "OuterIsLeft": 0,
    "Radius_Bottom": 25,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 15,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": -0.2,
    "Width": 105
  },
  "Questioning_Normal": {
    "Height": 68,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 18,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 18,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 92
  },
  "Sad": {
    "Height": 38,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 25,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 2,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": -0.5,
    "Width": 100
  },
  "Scared": {
    "Height": 85,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 8,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 48,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 100
  },
  "Scary": {
    "Height": 55,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 20,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 3,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": -0.45,
    "Width": 100
  },
  "Skeptic": {
    "Height": 100,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 25,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 25,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 100
  },
  "Skeptic_Alt": {
    "Height": 65,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": -15,
    "OuterIsLeft": 0,
    "Radius_Bottom": 25,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 2,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.3,
    "Width": 100
  },
  "Sleepy": {
    "Height": 32,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": -19,
    "OuterIsLeft": 0,
    "Radius_Bottom": 6,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 12,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 100
  },
  "Sleepy_Alt": {
    "Height": 24,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": -23,
    "OuterIsLeft": 0,
    "Radius_Bottom": 6,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 10,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 100
  },
  "Smug_Closed": {
    "Height": 18,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 8,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 0,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 18,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.05,
    "Width": 100
  },
  "Smug_Normal": {
    "Height": 55,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 15,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 20,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.1,
    "Width": 100
  },
  "Squint": {
    "Height": 28,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 2,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 8,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.28,
    "Slope_Top": 0.0,
    "Width": 100
  },
  "Surprised": {
    "Height": 112,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 40,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 40,
    "Radius_Top_Outer": 56,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 112
  },
  "Suspicious": {
    "Height": 55,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 8,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 20,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 100
  },
  "Suspicious_Alt": {
    "Height": 40,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": -8,
    "OuterIsLeft": 0,
    "Radius_Bottom": 8,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 15,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.2,
    "Width": 100
  },
  "Unimpressed": {
    "Height": 30,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 0,
    "OuterIsLeft": 0,
    "Radius_Bottom": 25,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 2,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 100
  },
  "Unimpressed_Alt": {
    "Height": 55,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": -8,
    "OuterIsLeft": 0,
    "Radius_Bottom": 40,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 2,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": 0.0,
    "Width": 100
  },
  "Worried": {
    "Height": 62,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": -4,
    "OuterIsLeft": 0,
    "Radius_Bottom": 25,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 15,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": -0.1,
    "Width": 100
  },
  "Worried_Alt": {
    "Height": 88,
    "Inverse_Offset_Bottom": 0,
    "Inverse_Offset_Top": 0,
    "Inverse_Radius_Bottom": 0,
    "Inverse_Radius_Top": 0,
    "OffsetX": 0,
    "OffsetY": 9,
    "OuterIsLeft": 0,
    "Radius_Bottom": 25,
    "Radius_Bottom_Outer": 0,
    "Radius_Top": 15,
    "Radius_Top_Outer": 0,
    "Slope_Bottom": 0.0,
    "Slope_Top": -0.2,
    "Width": 100
  }
};
window.EMOTIONS = [
  "Normal",
  "Angry",
  "Glee",
  "Happy",
  "Sad",
  "Worried",
  "Focused",
  "Annoyed",
  "Surprised",
  "Skeptic",
  "Frustrated",
  "Unimpressed",
  "Sleepy",
  "Suspicious",
  "Nervous",
  "Furious",
  "Scared",
  "Awe",
  "Excited",
  "Questioning",
  "Frozen",
  "Scary",
  "Curious",
  "Doubt",
  "Contempt",
  "Disgust",
  "Smug",
  "Dead",
  "Blush",
  "Squint"
];
window.EMOTION_PRESETS = {
  "Angry": {
    "left": "Angry",
    "lidCenter": null,
    "right": "Angry"
  },
  "Annoyed": {
    "left": "Annoyed_Alt",
    "lidCenter": null,
    "right": "Annoyed"
  },
  "Awe": {
    "left": "Awe",
    "lidCenter": "Awe",
    "right": "Awe"
  },
  "Blush": {
    "left": "Happy",
    "lidCenter": null,
    "right": "Happy"
  },
  "Contempt": {
    "left": "Contempt_Normal",
    "lidCenter": "Contempt_Squint",
    "right": "Contempt_Squint"
  },
  "Curious": {
    "left": "Curious_Normal",
    "lidCenter": "Curious_Normal",
    "right": "Curious_Big"
  },
  "Dead": {
    "left": "Dead",
    "lidCenter": "Dead",
    "right": "Dead"
  },
  "Disgust": {
    "left": "Disgust",
    "lidCenter": null,
    "right": "Disgust"
  },
  "Doubt": {
    "left": "Doubt",
    "lidCenter": "Doubt",
    "right": "Doubt"
  },
  "Excited": {
    "left": "Excited",
    "lidCenter": "Excited",
    "right": "Excited"
  },
  "Focused": {
    "left": "Focused",
    "lidCenter": null,
    "right": "Focused"
  },
  "Frozen": {
    "left": "Frozen",
    "lidCenter": null,
    "right": "Frozen"
  },
  "Frustrated": {
    "left": "Frustrated",
    "lidCenter": null,
    "right": "Frustrated"
  },
  "Furious": {
    "left": "Furious",
    "lidCenter": null,
    "right": "Furious"
  },
  "Glee": {
    "left": "Glee",
    "lidCenter": null,
    "right": "Glee"
  },
  "Happy": {
    "left": "Happy",
    "lidCenter": null,
    "right": "Happy"
  },
  "Nervous": {
    "left": "Nervous_Alt",
    "lidCenter": "Nervous_Alt",
    "right": "Nervous"
  },
  "Normal": {
    "left": "Normal_Alt",
    "lidCenter": "Normal_Alt",
    "right": "Normal"
  },
  "Questioning": {
    "left": "Questioning_Normal",
    "lidCenter": "Questioning_Normal",
    "right": "Questioning_Big"
  },
  "Sad": {
    "left": "Sad",
    "lidCenter": null,
    "right": "Sad"
  },
  "Scared": {
    "left": "Scared",
    "lidCenter": null,
    "right": "Scared"
  },
  "Scary": {
    "left": "Scary",
    "lidCenter": null,
    "right": "Scary"
  },
  "Skeptic": {
    "left": "Skeptic_Alt",
    "lidCenter": null,
    "right": "Skeptic"
  },
  "Sleepy": {
    "left": "Sleepy_Alt",
    "lidCenter": null,
    "right": "Sleepy"
  },
  "Smug": {
    "left": "Smug_Normal",
    "lidCenter": "Smug_Closed",
    "right": "Smug_Closed"
  },
  "Squint": {
    "left": "Squint",
    "lidCenter": "Squint",
    "right": "Squint"
  },
  "Surprised": {
    "left": "Surprised",
    "lidCenter": "Surprised",
    "right": "Surprised"
  },
  "Suspicious": {
    "left": "Suspicious_Alt",
    "lidCenter": null,
    "right": "Suspicious"
  },
  "Unimpressed": {
    "left": "Unimpressed_Alt",
    "lidCenter": null,
    "right": "Unimpressed"
  },
  "Worried": {
    "left": "Worried_Alt",
    "lidCenter": null,
    "right": "Worried"
  }
};
window.EMOTION_RGB = {
  "Angry": 16721920,
  "Annoyed": 16721920,
  "Awe": 16777215,
  "Blush": 16747696,
  "Contempt": 7907840,
  "Curious": 51320,
  "Dead": 8952319,
  "Disgust": 7907840,
  "Doubt": 51320,
  "Excited": 16762880,
  "Focused": 38600,
  "Frozen": 8545535,
  "Frustrated": 16721920,
  "Furious": 16721920,
  "Glee": 16762880,
  "Happy": 16762880,
  "Nervous": 38600,
  "Normal": 38600,
  "Questioning": 51320,
  "Sad": 20680,
  "Scared": 8545535,
  "Scary": 13107220,
  "Skeptic": 38600,
  "Sleepy": 10183910,
  "Smug": 16762880,
  "Squint": 38600,
  "Surprised": 16777215,
  "Suspicious": 38600,
  "Unimpressed": 38600,
  "Worried": 20680
};
window.EYE_COLOR_DIM = 0.8;
