// =============================================================================
// sccb_m5.cpp — StackChan-Companion (firmware/companion)
// =============================================================================
// OVERRIDE of the SCCB (camera control bus) from the esp32-camera library.
//
// Problem (diagnosed 2026-07-17): the PRECOMPILED esp32-camera component
// drives the SCCB through the ESP-IDF I2C driver (`i2c_master_cmd_begin`).
// But M5Unified drives the internal bus (pins 11/12, shared IMU/AXP/AW9523)
// with its OWN register implementation (`m5gfx::i2c`), NOT the IDF driver.
// Result: the native SCCB finds no IDF driver on that port → timeout (the
// GC0308 sensor IS there, see Camera::probePresent).
//
// Solution: esp32-camera exposes SCCB_Init/Use_Port/Deinit/Probe/Read/Write
// as GLOBAL (non-static) symbols. We REDEFINE them here to route the SCCB
// through `M5.In_I2C` — the SAME i2c as the IMU, hence serialized and free
// of bus conflicts. The linker picks our definitions thanks to the flag
// `-Wl,--allow-multiple-definition` (platformio.ini, env companion): the
// project objects come before the libesp32-camera.a archive.
//
// The GC0308 is an 8-bit sensor (register + value): only the 8-bit
// Read/Write are actually used; the 16-bit variants are stubs.
//
// ⚠ The SCCB shares M5.In_I2C with the IMU reads (100 Hz, Brain task) and
// the other users of the 11/12 bus. m5gfx::i2c is not mutexed: EVERY SCCB
// transaction is therefore taken under the bus lock (hal/I2cBus.h) — the
// Brain slips its IMU reads in between the writes (VOR stays alive even
// during camera init, ~300 register writes). These functions are called BY
// esp_camera_init itself: without the lock here, the driver's internal init
// phase would stay unarbitrated.
// =============================================================================

#include <M5Unified.h>
#include <cstdint>
#include "hal/I2cBus.h"

static constexpr uint32_t SCCB_FREQ = 100000;   // 100 kHz (same as In_I2C)

extern "C" {

int SCCB_Init(int pin_sda, int pin_scl) { (void)pin_sda; (void)pin_scl; return 0; }
int SCCB_Use_Port(int i2c_num)          { (void)i2c_num; return 0; }
int SCCB_Deinit(void)                   { return 0; }

// Sensor detection: probes the known camera addresses (7-bit) on the M5 bus.
// GC0308 (CoreS3) = 0x21. XCLK is already generated by esp_camera_init before
// this call → the sensor is clocked and acknowledges.
uint8_t SCCB_Probe(void) {
    // The CoreS3 only has a GC0308 at 0x21; we probe that single address.
    sce::i2cbus::Guard g;
    return M5.In_I2C.scanID(0x21, SCCB_FREQ) ? 0x21 : 0;
}

uint8_t SCCB_Read(uint8_t slv_addr, uint8_t reg) {
    sce::i2cbus::Guard g;
    return M5.In_I2C.readRegister8(slv_addr, reg, SCCB_FREQ);
}

uint8_t SCCB_Write(uint8_t slv_addr, uint8_t reg, uint8_t data) {
    // esp32-camera convention: 0 = OK, non-zero = error.
    sce::i2cbus::Guard g;
    return M5.In_I2C.writeRegister8(slv_addr, reg, data, SCCB_FREQ) ? 0 : 0xFF;
}

// ---- 16-bit variants (OV3660-class sensors): unused by the GC0308 ----
uint8_t SCCB_Read16(uint8_t slv_addr, uint16_t reg) {
    sce::i2cbus::Guard g;
    uint8_t v = 0;
    M5.In_I2C.readRegister(slv_addr, (uint8_t)(reg & 0xFF), &v, 1, SCCB_FREQ);
    return v;
}
uint8_t SCCB_Write16(uint8_t slv_addr, uint16_t reg, uint8_t data) {
    sce::i2cbus::Guard g;
    return M5.In_I2C.writeRegister8(slv_addr, (uint8_t)(reg & 0xFF), data,
                                    SCCB_FREQ) ? 0 : 0xFF;
}
int SCCB_Read_Addr16_Val16(uint8_t, uint16_t, uint16_t*) { return -1; }
int SCCB_Write_Addr16_Val16(uint8_t, uint16_t, uint16_t) { return -1; }

} // extern "C"
