#pragma once
// =============================================================================
// EyePresetsM5.h — StackChan-Companion
// =============================================================================
// esp32-eyes presets ported to the StackChan CoreS3 (eye area 320×160 px)
// Scale factor applied: ×2.5  (source 128×64 → 320×160)
//
// Originally generated by tools/generators/scale_presets.py, then RETOUCHED BY HAND
// (Cozmo art direction, hardware verdicts) — do NOT regenerate blindly.
// Source     : playfultechnology/esp32-eyes (AGPL-3.0)
//              luisllamasbinaburo/ESP32_Faces (AGPL-3.0)
//
// Notes:
//   - Slope_Top/Bottom are dimensionless ratios: NOT scaled
//   - Presets are written for the LEFT eye; EyeRig::mirrored flips slopes and
//     OffsetX for the right eye (and applies the global random mirror)
//   - The _Alt presets are the other eye of the asymmetric emotions
//   - EQUIDISTANCE (A2.17): OffsetX = 0 EVERYWHERE (the gap between eye
//     centres is the same for every emotion) — ONLY exception: Nervous_Alt
//     (small 50 px eye pulled toward the centre to keep the spacing)
//   - EMOTIONS_COUNT counts only the main presets (not the Alt ones)
// =============================================================================

#include "../EyeConfig.h"

// Normal
static const sce::EyeConfig Preset_Normal = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ 0,
    /* Height                         */ 100,
    /* Width                          */ 100,
    /* Slope_Top                      */ 0.00f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 20,
    /* Radius_Bottom                  */ 20,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Normal_Alt — one of the two eyes (side is RANDOM, via the global mirror,
// user verdict 2026-07-16) is SLIGHTLY shorter (92 vs 100), still vertically
// centred. Same width (Normal invariant).
static const sce::EyeConfig Preset_Normal_Alt = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ 0,
    /* Height                         */ 92,
    /* Width                          */ 100,
    /* Slope_Top                      */ 0.00f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 20,
    /* Radius_Bottom                  */ 20,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Happy
static const sce::EyeConfig Preset_Happy = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ 0,
    /* Height                         */ 25,
    /* Width                          */ 100,
    /* Slope_Top                      */ 0.00f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 25,
    /* Radius_Bottom                  */ 0,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Glee
// OffsetY +40 (user verdict 2026-07-16): the eyes LIVE IN THE UPPER HALF of
// the area (centre ~40 px, ±12 oscillation included) — joy that sparkles high.
// (a positive preset value means upward; the sign is flipped by
//  EyeRig::mirrored)
static const sce::EyeConfig Preset_Glee = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ 40,
    /* Height                         */ 20,
    /* Width                          */ 100,
    /* Slope_Top                      */ 0.00f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 20,
    /* Radius_Bottom                  */ 0,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 12,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Sad
static const sce::EyeConfig Preset_Sad = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ 0,
    /* Height                         */ 38,
    /* Width                          */ 100,
    /* Slope_Top                      */ -0.50f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 2,
    /* Radius_Bottom                  */ 25,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Focused
static const sce::EyeConfig Preset_Focused = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ 0,
    /* Height                         */ 35,
    /* Width                          */ 100,
    /* Slope_Top                      */ 0.20f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 8,
    /* Radius_Bottom                  */ 2,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Surprised
// Radius_Top_Outer 56 (user 2026-07-16, raised after the first verdict):
// top OUTER corners at the maximum (Width/2 — a full quarter circle) —
// the wide-eyed look "opens up" toward the temples.
static const sce::EyeConfig Preset_Surprised = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ 0,
    /* Height                         */ 112,
    /* Width                          */ 112,
    /* Slope_Top                      */ 0.00f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 40,
    /* Radius_Bottom                  */ 40,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0,
    /* Radius_Top_Outer               */ 56,
    /* Radius_Bottom_Outer            */ 0
};

// Frustrated
static const sce::EyeConfig Preset_Frustrated = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ -12,
    /* Height                         */ 30,
    /* Width                          */ 100,
    /* Slope_Top                      */ 0.00f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 0,
    /* Radius_Bottom                  */ 25,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Furious
static const sce::EyeConfig Preset_Furious = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ 0,
    /* Height                         */ 75,
    /* Width                          */ 100,
    /* Slope_Top                      */ 0.40f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 5,
    /* Radius_Bottom                  */ 20,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Scared
// User retouch 2026-07-16: height raised (70→85), bottom nearly square
// (Radius_Bottom 8, like Suspicious). 2nd verdict: "the MIDDLE of the eye
// must be the highest point" → DOME (zero slope, Radius_Top 48 ≈ Width/2:
// the top rounds into a bell, apex at the centre). Bonus: no slope/corner
// junction left at all (the old 2026-07-11 step artefact is gone by
// construction).
static const sce::EyeConfig Preset_Scared = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ 0,
    /* Height                         */ 85,
    /* Width                          */ 100,
    /* Slope_Top                      */ 0.00f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 48,
    /* Radius_Bottom                  */ 8,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Awe
// Redefined by user 2026-07-16 (2nd pass): Awe = SURPRISED FLIPPED
// vertically (top becomes bottom) — same 112×112 template, the OUTER corner
// widened at the BOTTOM instead of the top. NO slope at all (the 1st pass
// Slope_Bottom recreated the old "line" artefact — removed).
// 3rd pass: bottom outer cut 56→48, top outer raised 40→46 (balance).
static const sce::EyeConfig Preset_Awe = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ 0,
    /* Height                         */ 112,
    /* Width                          */ 112,
    /* Slope_Top                      */ 0.00f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 40,
    /* Radius_Bottom                  */ 40,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0,
    /* Radius_Top_Outer               */ 46,
    /* Radius_Bottom_Outer            */ 48
};

// Angry
static const sce::EyeConfig Preset_Angry = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ 0,
    /* Height                         */ 50,
    /* Width                          */ 100,
    /* Slope_Top                      */ 0.30f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 5,
    /* Radius_Bottom                  */ 30,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Annoyed
static const sce::EyeConfig Preset_Annoyed = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ 0,
    /* Height                         */ 30,
    /* Width                          */ 100,
    /* Slope_Top                      */ 0.00f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 0,
    /* Radius_Bottom                  */ 25,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Skeptic
static const sce::EyeConfig Preset_Skeptic = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ 0,
    /* Height                         */ 100,
    /* Width                          */ 100,
    /* Slope_Top                      */ 0.00f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 25,
    /* Radius_Bottom                  */ 25,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Unimpressed
static const sce::EyeConfig Preset_Unimpressed = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ 0,
    /* Height                         */ 30,
    /* Width                          */ 100,
    /* Slope_Top                      */ 0.00f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 2,
    /* Radius_Bottom                  */ 25,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Sleepy
// Sleepy — Cozmo rework (2026-07-11, docs/assets/cozmo.jpg "Sleepy Eyes"):
// FLAT half-closed lid, no bevels (slopes of -0.5 left a residual "line"
// under the eyes — PLAYBOOK-HW §4e).
// OffsetY: PINNED TO THE BOTTOM OF THE EYE ZONE (user 08-03), which SUPERSEDES
// the verdict of 2026-07-12 recorded here — that one asked for the lower edge to
// sit where a NORMAL eye has it (70/2 = 35 below centre), and that is what -19
// gave. It is written down rather than overwritten: a preset value with a user's
// name on it is not a free parameter, and the next reader has to be able to see
// that the earlier answer was replaced on purpose and not lost.
//
// The zone is 160 px tall and centred at EYE_CY = 80, so its floor is +80 from
// centre. The eyes rest TWENTY pixels above it, at +60 (user 08-03) — low
// enough to read as "sinking", not so low that they merge with the status band.
// Nothing can push them off that line either: the Brain freezes every VERTICAL
// channel for Sleepy (gaze y, breathing, squashY) while leaving the horizontal
// ones alone, so the rest is genuinely still and the eyes can still glance
// sideways. 60 - 32/2 = 44; the sign is flipped by EyeRig::mirrored, so a
// NEGATIVE preset value means downward. The lid still drops onto a bottom that
// does not move — the A2.17 falling-lid invariant is untouched, only the line
// it falls to has.
static const sce::EyeConfig Preset_Sleepy = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ -44,
    /* Height                         */ 32,
    /* Width                          */ 100,
    /* Slope_Top                      */ 0.00f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 12,
    /* Radius_Bottom                  */ 6,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Suspicious
static const sce::EyeConfig Preset_Suspicious = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ 0,
    /* Height                         */ 55,
    /* Width                          */ 100,
    /* Slope_Top                      */ 0.00f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 20,
    /* Radius_Bottom                  */ 8,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Nervous (formerly Squint, renamed by user 2026-07-16) — the "wide open"
// eye of the nervous pair (the other one is Nervous_Alt, the small squinting
// one)
static const sce::EyeConfig Preset_Nervous = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ -8,
    /* Height                         */ 88,
    /* Width                          */ 88,
    /* Slope_Top                      */ 0.00f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 20,
    /* Radius_Bottom                  */ 20,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Worried
// OffsetY -4 (user verdict 2026-07-16): BOTTOM edges of both eyes ALIGNED at
// +35 px from the centre (same anchor as Sleepy) — 35 - 62/2 = 4 downward.
static const sce::EyeConfig Preset_Worried = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ -4,
    /* Height                         */ 62,
    /* Width                          */ 100,
    /* Slope_Top                      */ -0.10f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 15,
    /* Radius_Bottom                  */ 25,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Worried_Alt
// Bottom edge aligned at +35: 35 - 88/2 = -9 → preset +9 (upward).
static const sce::EyeConfig Preset_Worried_Alt = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ 9,
    /* Height                         */ 88,
    /* Width                          */ 100,
    /* Slope_Top                      */ -0.20f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 15,
    /* Radius_Bottom                  */ 25,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Annoyed_Alt
// OffsetY +9 (user verdict 2026-07-16): TOP edges aligned with Preset_Annoyed
// (top at -15 px from the centre: -15 + 12/2 = -9 → preset +9, upward).
static const sce::EyeConfig Preset_Annoyed_Alt = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ 9,
    /* Height                         */ 12,
    /* Width                          */ 100,
    /* Slope_Top                      */ 0.00f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 0,
    /* Radius_Bottom                  */ 10,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Skeptic_Alt
static const sce::EyeConfig Preset_Skeptic_Alt = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ -15,
    /* Height                         */ 65,
    /* Width                          */ 100,
    /* Slope_Top                      */ 0.30f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 2,
    /* Radius_Bottom                  */ 25,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Unimpressed_Alt
static const sce::EyeConfig Preset_Unimpressed_Alt = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ -8,
    /* Height                         */ 55,
    /* Width                          */ 100,
    /* Slope_Top                      */ 0.00f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 2,
    /* Radius_Bottom                  */ 40,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Sleepy_Alt
// Sleepy_Alt (left eye) — same Cozmo rework, slightly more closed
// (asymmetry taken from the cozmo.jpg sheet). Pinned to the same floor as its
// twin, which is the whole point of the pair: 60 - 24/2 = 48. Computed from the
// SAME +60 line, so the two eyes rest on one edge however their heights differ —
// derive it from the height, never copy the number across.
static const sce::EyeConfig Preset_Sleepy_Alt = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ -48,
    /* Height                         */ 24,
    /* Width                          */ 100,
    /* Slope_Top                      */ 0.00f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 10,
    /* Radius_Bottom                  */ 6,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Suspicious_Alt
static const sce::EyeConfig Preset_Suspicious_Alt = {
    /* OffsetX                        */ 0,
    /* OffsetY                        */ -8,
    /* Height                         */ 40,
    /* Width                          */ 100,
    /* Slope_Top                      */ 0.20f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 15,
    /* Radius_Bottom                  */ 8,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

// Nervous_Alt — the SMALL eye (50×50). OffsetX +20 (user verdict
// 2026-07-16): pulled toward the centre of the face to compensate for its
// reduced half-width (25 vs 50) — the edge-to-edge spacing stays nearly the
// same as for the other emotions. ONLY exception to the "OffsetX = 0"
// (equidistance) rule.
static const sce::EyeConfig Preset_Nervous_Alt = {
    /* OffsetX                        */ 20,
    /* OffsetY                        */ 0,
    /* Height                         */ 50,
    /* Width                          */ 50,
    /* Slope_Top                      */ 0.00f,
    /* Slope_Bottom                   */ 0.00f,
    /* Radius_Top                     */ 12,
    /* Radius_Bottom                  */ 12,
    /* Inverse_Radius_Top             */ 0,
    /* Inverse_Radius_Bottom          */ 0,
    /* Inverse_Offset_Top             */ 0,
    /* Inverse_Offset_Bottom          */ 0
};

